# Version: 0.0.1

FROM centos

# env vars
ENV PW admin
ENV INSTALL_DIR /home/www-data
ENV W2P_DIR $INSTALL_DIR/web2py
ENV CERT_PASS web2py

# update ubuntu and install necessary packages
COPY kalan-core-centos.fil /opt/kalan/sw/kalan-core-centos.fil
RUN yum -y update
RUN yum -y install $(cat /opt/kalan/sw/kalan-core-centos.fil)
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm  && \
	yum -y install nginx && \
	yum -y install build-essential python-dev libxml2-dev python-pip unzip wget supervisor && \
	pip install --upgrade pip  && \
	pip install setuptools --no-use-wheel --upgrade && \
	pip install --upgrade uwsgi

RUN yum -y install firewalld

RUN mkdir /etc/nginx/conf.d/web2py && \
	mkdir -p /opt/kalan/sw/pip

COPY python-req.txt /etc/python-req.txt
RUN pip install --download /opt/kalan/sw/pip -r /etc/python-req.txt && \
	pip install -r /etc/python-req.txt --no-index --find-links file:///opt/kalan/sw/pip

# copy nginx config files from repo
COPY gzip_static.conf /etc/nginx/conf.d/web2py/gzip_static.conf
COPY gzip.conf /etc/nginx/conf.d/web2py/gzip.conf
COPY web2py /etc/nginx/sites-available/web2py

# setup nginx
#RUN ln -s /etc/nginx/sites-available/web2py /etc/nginx/sites-enabled/web2py
#RUN rm /etc/nginx/sites-enabled/default
RUN mkdir /etc/nginx/ssl && cd /etc/nginx/ssl && \
	openssl genrsa -passout pass:$CERT_PASS 1024 > web2py.key && \
	chmod 400 web2py.key && \
	openssl req -new -x509 -nodes -sha1 -days 1780 -subj "/C=MX/ST=Mexico/L=mex/O=Dis/CN=www.example.com" -key web2py.key > web2py.crt && \
	openssl x509 -noout -fingerprint -text < web2py.crt > web2py.info && \
	mkdir /etc/uwsgi && \
	mkdir /var/log/uwsgi

# copy Emperor config files from repo
COPY web2py.ini /etc/uwsgi/web2py.ini
COPY uwsgi-emperor.conf /etc/init/uwsgi-emperor.conf

# copy Supervisor config file from repo
COPY supervisor-app.conf /etc/supervisor/conf.d/

# get and install web2py
RUN mkdir $INSTALL_DIR && cd $INSTALL_DIR && \
   wget http://www.web2py.com/examples/static/web2py_src.zip && \
	unzip web2py_src.zip && \
	rm web2py_src.zip && \
	mv web2py/handlers/wsgihandler.py web2py/wsgihandler.py  && \
	cd $W2P_DIR

RUN chown -R nginx:nginx web2py && \
	sudo -u nginx python -c "from gluon.main import save_password; save_password('$PW',80)" && \
	sudo -u nginx python -c "from gluon.main import save_password; save_password('$PW',443)" && \
	nginx

#RUN firewall-cmd --permanent --zone=public --add-service=http  && \
	#firewall-cmd --permanent --zone=public --add-service=https && \
	#firewall-cmd --reload

EXPOSE 80 443 8000

WORKDIR $W2P_DIR

#CMD ["supervisord", "-n"]
