# Version: 0.0.2

FROM ubuntu:latest

# env vars
ENV PW admin
ENV INSTALL_DIR /opt/k-w2p
ENV W2P_DIR $INSTALL_DIR/web2py
ENV CERT_PASS web2py

# update ubuntu and install necessary packages
RUN apt-get update && \
	apt-get autoremove && \
	apt-get autoclean

COPY kalan-core-apt-get.fil /opt/kalan/sw/kalan-core-apt-get.fil

RUN apt-get -y install $(cat /opt/kalan/sw/kalan-core-apt-get.fil)

RUN pip install setuptools --no-use-wheel --upgrade && \
   pip install pip --no-use-wheel --upgrade && \
	PIPPATH=`which pip` && \
	$PIPPATH install --upgrade uwsgi && \
	mkdir -p /opt/kalan/sw/pip

COPY kalan-core-apt-get.fil /opt/kalan/sw/kalan-core-apt-get.fil

RUN apt-get -y install $(cat /opt/kalan/sw/kalan-core-apt-get.fil)

COPY python-req-apt-get.txt /etc/python-req-apt-get.txt

RUN pip install --download /opt/kalan/sw/pip -r /etc/python-req-apt-get.txt && \
	pip install -r /etc/python-req-apt-get.txt --no-index --find-links file:///opt/kalan/sw/pip


# copy Supervisor config file from repo
COPY supervisor-app.conf /etc/supervisor/conf.d/


# get and install web2py
RUN mkdir $INSTALL_DIR
RUN cd $INSTALL_DIR
RUN useradd -s /usr/sbin/nologin -r -M -d /dev/null kalan
COPY web2py $INSTALL_DIR
	chown -R kalan:kalan $W2P_DIR && \
	cd $W2P_DIR
RUN sudo -u www-data python  $W2P_DIR/web2py.py --nogui -i 0.0.0.0 -p 8888 -a "<recycle>" && \
	sudo -u www-data python -c "from gluon.main import save_password; save_password('$PW',8888)"

EXPOSE 8888
WORKDIR $W2P_DIR

CMD ["supervisord", "-n"]
