# Version: 0.0.2

FROM ubuntu:14.04.3

# update ubuntu and install necessary packages
RUN apt-get update && \
	apt-get autoremove && \
	apt-get autoclean && \
	mkdir -p /var/kalan/sw/pip

COPY kalan-core-apt-get.fil /var/kalan/sw/kalan-core-apt-get.fil

RUN apt-get -y install $(cat /var/kalan/sw/kalan-core-apt-get.fil)

RUN pip install setuptools --no-use-wheel --upgrade && \
  pip install pip --no-use-wheel --upgrade && \
	PIPPATH=`which pip`

COPY python-req-apt-get.txt /var/kalan/sw/python-req-apt-get.txt

RUN pip install --download /var/kalan/sw/pip -r /var/kalan/sw/python-req-apt-get.txt && \
   pip install -r /var/kalan/sw/python-req-apt-get.txt --no-index --find-links file:///var/kalan/sw/pip


# copy Supervisor config file from repo
COPY supervisor-app.conf /etc/supervisor/conf.d/



RUN useradd -s /usr/sbin/nologin -r -M -d /dev/null kcontainer


EXPOSE 8888 8443
WORKDIR $W2P_DIR

COPY kalan-container /var/kalan-container
RUN mv -rf /var/kalan-container/web2py/applications /var/kalan-container/web2py/applications-backup
