FROM k-w2p

ENV KALAN_PROXY_TO 127.0.0.1

COPY httpd-foreground /usr/local/bin/
RUN chmod 775 /usr/local/bin/httpd-foreground
EXPOSE 80 443
CMD ["/usr/local/bin/httpd-foreground"]
RUN apt-get install apache2
