FROM k-w2p
ENV KALAN_PROXY_TO 127.0.0.1
ENV HTTPD_PREFIX /usr/local/apache2
ENV PATH $PATH:$HTTPD_PREFIX/bin
RUN mkdir -p "$HTTPD_PREFIX" \
	&& chown www-data:www-data "$HTTPD_PREFIX"
WORKDIR $HTTPD_PREFIX

# install httpd runtime dependencies
# https://httpd.apache.org/docs/2.4/install.html#requirements
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		libapr1 \
		libaprutil1 \
		libapr1-dev \
		libaprutil1-dev \
		libpcre++0 \
		libssl1.0.0 \
	&& rm -r /var/lib/apt/lists/*

# see https://httpd.apache.org/download.cgi#verify
RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys A93D62ECC3C8EA12DB220EC934EA76E6791485A8

ENV HTTPD_VERSION 2.4.18
ENV HTTPD_BZ2_URL https://www.apache.org/dist/httpd/httpd-$HTTPD_VERSION.tar.bz2

RUN buildDeps=' \
		ca-certificates \
		curl \
		bzip2 \
		gcc \
		libpcre++-dev \
		libssl-dev \
		make \
	' \
	set -x \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends $buildDeps \
	&& rm -r /var/lib/apt/lists/* \
	&& curl -SL "$HTTPD_BZ2_URL" -o httpd.tar.bz2 \
	&& curl -SL "$HTTPD_BZ2_URL.asc" -o httpd.tar.bz2.asc \
	&& gpg --verify httpd.tar.bz2.asc \
	&& mkdir -p src/httpd \
	&& tar -xvf httpd.tar.bz2 -C src/httpd --strip-components=1 \
	&& rm httpd.tar.bz2* \
	&& cd src/httpd \
	&& ./configure --enable-so --enable-ssl --prefix=$HTTPD_PREFIX --enable-mods-shared=most \
	&& make -j"$(nproc)" \
	&& make install \
	&& cd ../../ \
	&& rm -r src/httpd \ 
	&& sed -ri ' \
		s!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g; \
		s!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g; \
		' /usr/local/apache2/conf/httpd.conf

COPY httpd-foreground /usr/local/bin/
RUN chmod 775 /usr/local/bin/httpd-foreground
COPY modsecurity-2.9.0.tar.gz /usr/local/apache2/
RUN cd /usr/local/apache2/ && \
tar xzf modsecurity-2.9.0.tar.gz && \
cd modsecurity-2.9.0 && \
./configure && \
make install 

RUN apt-get purge -y --auto-remove $buildDeps

COPY owasp-modsecurity-crs /usr/local/apache2/conf/modsecurity-crs
RUN cd /usr/local/apache2/conf/modsecurity-crs && \
cp modsecurity_crs_10_setup.conf.example modsecurity_crs_10_config.conf && \
> /usr/local/apache2/conf/modsecurity-crs/base_rules/modsecurity_crs_99_excepciones.conf && \
echo "#excepciones modsecurity v1.0" >> /usr/local/apache2/confd/modsecurity-crs/base_rules/modsecurity_crs_99_excepciones.conf && \
echo 'SecRuleRemoveByID 981173 "pass"' >> /usr/local/apache2/conf/modsecurity-crs/base_rules/modsecurity_crs_99_excepciones.conf && \
echo 'SecRuleRemoveByID 981203 "pass"' >> /usr/local/apache2/conf/modsecurity-crs/base_rules/modsecurity_crs_99_excepciones.conf && \
echo 'SecRuleRemoveByID 960017 "pass"' >> /usr/local/apache2/conf/modsecurity-crs/base_rules/modsecurity_crs_99_excepciones.conf
EXPOSE 80 443
CMD ["/usr/local/bin/httpd-foreground"]
