data:
  build: k-w2p
  command: echo "creating data container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/data:/var/kalan-container/k-w2p
  labels:
    - "com.kalan.provision=kalan"

logs:
  image: kalan_data
  command: echo "creating logs container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/logs:/usr/local/apache2/logs
  labels:
    - "com.kalan.provision=kalan"
  links:
   - web2py
   - admin
   
web2py:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8888
  command: init
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped

admin:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8443
  command: initadmin admin
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped
  
httpd:
  build: k-httpd
  volumes_from:
    - logs
  ports:
   - "80:80"
   - "443:443"
  links:
   - web2py
   - admin
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped

#meteor:
#  build: k-meteor
#  command: start admin
#  links:
#   - mongo:mongodb
#  ports:
#   - "3000:3000"
#  - "3001:3001"
#  volumes:
#   - $HOME/kalan-data/provisions/kalan/met:/opt/application
#  environment:
#   - MONGO_URL=mongodb://admin:EgCq0fQT2eOJ@mongodb
#  restart: unless-stopped

#mongoadmin:
#  build: k-mongoadmin
#  links:
#   - mongo:mongodb
#  ports:
#   - "1234:1234"
#  restart: unless-stopped
  
mongo:
  build: k-mongo
  #volumes_from:
  #  - mongodata
  #command: mongod --nojournal --smallfiles --quiet --logpath=/dev/null
  #command: /run.sh
  volumes:
    - $HOME/kalan-data/provisions/kalan/mongo:/data/db
  ports:
    - "27017:27017"
    - "28017:28017" 
  environment:
    - MONGODB_PASS=EgCq0fQT2eOJ
  restart: unless-stopped
  
#mongodata:  
#  image: mongo:3
#  volumes:
#    - $HOME/kalan-data/provisions/kalan/mongo:/data/db
#  command: --break-mongo
