data:
  build: k-w2p
  command: echo "creating data container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/data:/var/kalan-container/k-w2p
  labels:
    - "com.kalan.provision=kalan"
    

logs:
  image: kalan_data
  command: echo "creating logs container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/logs:/usr/local/apache2/logs
  labels:
    - "com.kalan.provision=kalan"

web2py:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8888
  command: init
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped

admin:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8443
  command: initadmin admin
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped
  
httpd:
  build: k-httpd
  volumes_from:
    - data
  ports:
   - "80:80"
   - "443:443"
  links:
   - web2py
   - admin
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped

mongo:
  image: mongo:latest
  restart: unless-stopped

#dashboard:
#  build: k-meteor
#  dockerfile: dockerfile-dev
#  ports:
#   - "3000:3000"
#  links:
#   - mongo
#  environment:
#   - MONGO_URL=mongodb://mongo/meteor
#   - ROOT_URL=http://localhost:3000
#   - MAIL_URL=smtp://some.mailserver.com:25
#  restart: unless-stopped
