data:
  build: k-w2p
  command: echo "creating data container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/data:/var/kalan-container/k-w2p
logs:
  image: kalan_k-w2p
  command: echo "creating logs container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/logs:/usr/local/apache2/logs
web2py:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8888
  command: init


admin:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8443
  command: initadmin admin

httpd:
  build: k-httpd
  volumes_from:
    - data
  ports:
   - "80:80"
   - "443:443"
  links:
   - web2py
   - admin
