data:
  build: k-w2p
  command: echo "creating data container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/data:/var/kalan-container/k-w2p
  labels:
    - "com.kalan.provision=kalan"
  restart: no
logs:
  image: kalan_data
  command: echo "creating logs container in compose"
  volumes:
    - $HOME/kalan-data/provisions/kalan/logs:/usr/local/apache2/logs
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped
web2py:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8888
  command: init
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped

admin:
  image: kalan_data
  volumes_from:
    - data
  ports:
   - 8443
  command: initadmin admin
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped
  
httpd:
  build: k-httpd
  volumes_from:
    - data
  ports:
   - "80:80"
   - "443:443"
  links:
   - web2py
   - admin
  labels:
    - "com.kalan.provision=kalan"
  restart: unless-stopped
