# Set the base image to centos
FROM centos

# File Author / Maintainer
MAINTAINER tadeo gutierrez

# Update the repository sources list
RUN yum -y install git sudo whiptail dialog python wget curl
RUN git clone --recursive https://github.com/dlintec/kalan.git /opt/kalan
RUN chmod +x /opt/kalan/kalan-setup.sh
RUN /opt/kalan/kalan-setup.sh
RUN /opt/kalan/scripts/install-python.sh
#RUN /opt/kalan/kalan-instalacion.sh postinstall
CMD [ "sh", "-c", "/opt/kalan-instalacion.sh", "postinstall" ]
