# Set the base image to centos
FROM centos

# File Author / Maintainer
MAINTAINER tadeo gutierrez

# Update the repository sources list

RUN git clone --recursive https://github.com/dlintec/kalan.git /opt/kalan
RUN chmod +x /opt/kalan/kalan-instalacion.sh
RUN /opt/kalan/kalan-instalacion.sh scripts
