# Set the base image to centos
FROM centos

# File Author / Maintainer
MAINTAINER tadeo gutierrez

# Update the repository sources list
RUN yum -y install git sudo whiptail dialog
RUN git clone --recursive https://github.com/dlintec/kalan.git /opt/kalan
RUN chmod +x /opt/kalan/kalan-instalacion.sh
RUN /opt/kalan/kalan-instalacion.sh scripts
RUN /opt/kalan/scripts/instalar-paquetes.sh
#RUN /opt/kalan/kalan-instalacion.sh postinstall
CMD [ "sh", "-c", "/opt/kalan-instalacion.sh", "postinstall" ]
