FROM ubuntu:14.04.3
MAINTAINER kalan "info@dlintec.com"
#RUN update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
RUN "sh" "-c" "echo nameserver 8.8.8.8 >> /etc/resolv.conf"
RUN apt-get update && \
  apt-get -y dist-upgrade && \
  apt-get install -y curl npm && \
  curl https://install.meteor.com/ | sh

RUN npm install npm -g  && \
  npm cache clean -f  && \
  npm install -g n && \
  n stable && \
  npm install -g orion-cli && \
  ln -sf /usr/local/n/versions/node/5.4.1/bin/node /usr/bin/node
  

mkdir -p /opt/application
WORKDIR /opt/application
EXPOSE 3000

COPY ./docker-entrypoint.sh /opt/docker-entrypoint.sh
RUN chmod -R 775 /opt/docker-entrypoint.sh && \

ENTRYPOINT ["/opt/docker-entrypoint.sh"]
CMD [ "meteor" ]


