FROM ubuntu:14.04.3
MAINTAINER kalan "info@dlintec.com"
#RUN update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
RUN apt-get update && \
  apt-get -y dist-upgrade && \
  apt-get install -y curl && \
  curl https://install.meteor.com/ | sh

RUN sudo npm install npm -g  && \
  npm cache clean -f  && \
  sudo npm install -g n && \
  sudo n stable && \
  sudo npm install -g orion-cli && \
  sudo ln -sf /usr/local/n/versions/node/5.4.1/bin/node /usr/bin/node
  
  
WORKDIR /opt/application
EXPOSE 3000
CMD [ "meteor" ]
