FROM ubuntu:14.04.3
MAINTAINER kalan "info@dlintec.com"
#RUN update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
RUN "sh" "-c" "echo nameserver 8.8.8.8 >> /etc/resolv.conf"
RUN apt-get update && \
  apt-get -y dist-upgrade && \
  apt-get install -y curl npm && \
  curl https://install.meteor.com/ | sh

RUN npm install npm -g  && \
  npm cache clean -f  && \
  npm install -g n && \
  n stable && \
  npm install -g orion-cli && \
  ln -sf /usr/local/n/versions/node/5.4.1/bin/node /usr/bin/node
  

RUN mkdir -p /opt/application
WORKDIR /opt/application
EXPOSE 3000

COPY ./docker-entrypoint.sh /opt/docker-entrypoint.sh
RUN chmod -R 775 /opt/docker-entrypoint.sh 

ENTRYPOINT ["/opt/docker-entrypoint.sh"]
CMD [ "meteor" ]

RUN cd /opt && \
  meteor create default && \
  cd /opt/default
  
RUN  meteor add \
coffeescript \
mquandalle:jade \
mquandalle:stylus \
yasinuslu:blaze-meta \
dfischer:prerenderio \
tmeasday:publish-counts \
xorax:multiple-callbacks \
aldeed:collection2 \
fastclick \
reactive-var \
momentjs:moment \
mrt:moment-timezone \
raix:handlebar-helpers \
fortawesome:fontawesome \
alanning:roles \
accounts-password \
meteorhacks:aggregate \
http \
meteorhacks:unblock \
kyleking:customizable-bootstrap-stylus \
u2622:persistent-session \
aldeed:autoform \
percolate:momentum \
matb33:collection-hooks \
lepozepo:publish-with-relations \
ongoworks:security \
email \
browser-policy \
nimble:restivus \
kadira:flow-router \
kadira:blaze-layout \
standard-minifiers \
meteor-base \
mobile-experience \
mongo \
blaze-html-templates \
session \
jquery \
tracker \
logging \
reload \
random \
ejson \
spacebars \
check

#wizonesolutions:canonical 
