FROM python:2.7

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD COPY requirements.txt /usr/src/app/
ONBUILD RUN pip install --no-cache-dir -r requirements.txt

ONBUILD COPY . /usr/src/app

COPY kalan-core-apt-get.fil /usr/src/app/

RUN apt-get -y install $(cat /usr/src/app/kalan-core-apt-get.fil)
